"""update_wallet_sessions_schema

Revision ID: 2d78829cde30
Revises: ed70b125a093
Create Date: 2025-10-30 22:12:00.146734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d78829cde30'
down_revision: Union[str, Sequence[str], None] = 'ed70b125a093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_sessions', sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('wallet_sessions', sa.Column('refresh_jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('wallet_sessions', sa.Column('refresh_expires_at', sa.DateTime(), nullable=False))
    op.add_column('wallet_sessions', sa.Column('revoked', sa.Boolean(), nullable=False))
    op.add_column('wallet_sessions', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_wallet_sessions_is_revoked'), table_name='wallet_sessions')
    op.drop_index(op.f('ix_wallet_sessions_token_jti'), table_name='wallet_sessions')
    op.create_index(op.f('ix_wallet_sessions_jti'), 'wallet_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_wallet_sessions_refresh_jti'), 'wallet_sessions', ['refresh_jti'], unique=True)
    op.create_index(op.f('ix_wallet_sessions_revoked'), 'wallet_sessions', ['revoked'], unique=False)
    op.drop_column('wallet_sessions', 'token_jti')
    op.drop_column('wallet_sessions', 'is_revoked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_sessions', sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('wallet_sessions', sa.Column('token_jti', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_wallet_sessions_revoked'), table_name='wallet_sessions')
    op.drop_index(op.f('ix_wallet_sessions_refresh_jti'), table_name='wallet_sessions')
    op.drop_index(op.f('ix_wallet_sessions_jti'), table_name='wallet_sessions')
    op.create_index(op.f('ix_wallet_sessions_token_jti'), 'wallet_sessions', ['token_jti'], unique=True)
    op.create_index(op.f('ix_wallet_sessions_is_revoked'), 'wallet_sessions', ['is_revoked'], unique=False)
    op.drop_column('wallet_sessions', 'last_used_at')
    op.drop_column('wallet_sessions', 'revoked')
    op.drop_column('wallet_sessions', 'refresh_expires_at')
    op.drop_column('wallet_sessions', 'refresh_jti')
    op.drop_column('wallet_sessions', 'jti')
    # ### end Alembic commands ###
