"""Change contract primary key from id to policy_id

Revision ID: 93acdb8c9c24
Revises: bd405f30c556
Create Date: 2025-11-16 16:50:22.364018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93acdb8c9c24'
down_revision: Union[str, Sequence[str], None] = 'bd405f30c556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Drop all foreign key constraints that reference contracts.id
    op.drop_constraint(op.f('projects_contract_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('protocols_contract_id_fkey'), 'protocols', type_='foreignkey')
    op.drop_constraint(op.f('transactions_contract_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('utxos_contract_id_fkey'), 'utxos', type_='foreignkey')

    # Step 2: Add new contract_policy_id columns to referencing tables
    op.add_column('projects', sa.Column('contract_policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('protocols', sa.Column('contract_policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('transactions', sa.Column('contract_policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('utxos', sa.Column('contract_policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Step 3: Drop old contract_id columns
    op.drop_column('projects', 'contract_id')
    op.drop_column('protocols', 'contract_id')
    op.drop_column('transactions', 'contract_id')
    op.drop_column('utxos', 'contract_id')

    # Step 4: Drop the contracts.id column and its index
    op.drop_index(op.f('ix_contracts_policy_id'), table_name='contracts')
    op.drop_column('contracts', 'id')

    # Step 5: Make policy_id the primary key
    op.create_primary_key('contracts_pkey', 'contracts', ['policy_id'])

    # Step 6: Create new foreign key constraints referencing contracts.policy_id
    op.create_foreign_key(None, 'projects', 'contracts', ['contract_policy_id'], ['policy_id'])
    op.create_foreign_key(None, 'protocols', 'contracts', ['contract_policy_id'], ['policy_id'])
    op.create_foreign_key(None, 'transactions', 'contracts', ['contract_policy_id'], ['policy_id'])
    op.create_foreign_key(None, 'utxos', 'contracts', ['contract_policy_id'], ['policy_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utxos', sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'utxos', type_='foreignkey')
    op.create_foreign_key(op.f('utxos_contract_id_fkey'), 'utxos', 'contracts', ['contract_id'], ['id'])
    op.drop_column('utxos', 'contract_policy_id')
    op.add_column('transactions', sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_contract_id_fkey'), 'transactions', 'contracts', ['contract_id'], ['id'])
    op.drop_column('transactions', 'contract_policy_id')
    op.add_column('protocols', sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'protocols', type_='foreignkey')
    op.create_foreign_key(op.f('protocols_contract_id_fkey'), 'protocols', 'contracts', ['contract_id'], ['id'])
    op.drop_column('protocols', 'contract_policy_id')
    op.add_column('projects', sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_contract_id_fkey'), 'projects', 'contracts', ['contract_id'], ['id'])
    op.drop_column('projects', 'contract_policy_id')
    op.add_column('contracts', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('contracts_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_contracts_policy_id'), 'contracts', ['policy_id'], unique=True)
    # ### end Alembic commands ###
