"""Add source code and compilation fields to contracts

Revision ID: bd405f30c556
Revises: 45eec720154e
Create Date: 2025-11-16 12:13:37.557944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd405f30c556'
down_revision: Union[str, Sequence[str], None] = '45eec720154e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('source_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('contracts', sa.Column('source_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('contracts', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('contracts', sa.Column('compilation_params', sa.JSON(), nullable=True))
    op.add_column('contracts', sa.Column('compiled_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_contracts_source_hash'), 'contracts', ['source_hash'], unique=False)
    op.drop_constraint(op.f('wallet_sessions_wallet_id_fkey'), 'wallet_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'wallet_sessions', 'wallets', ['wallet_id'], ['id'])
    op.drop_index(op.f('ix_wallets_payment_key_hash'), table_name='wallets')
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.create_index(op.f('ix_wallets_payment_key_hash'), 'wallets', ['id'], unique=False)
    op.drop_constraint(None, 'wallet_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('wallet_sessions_wallet_id_fkey'), 'wallet_sessions', 'wallets', ['wallet_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_contracts_source_hash'), table_name='contracts')
    op.drop_column('contracts', 'compiled_at')
    op.drop_column('contracts', 'compilation_params')
    op.drop_column('contracts', 'version')
    op.drop_column('contracts', 'source_hash')
    op.drop_column('contracts', 'source_code')
    # ### end Alembic commands ###
