"""Add wallet security and session management

Revision ID: ed70b125a093
Revises: 234839046d28
Create Date: 2025-10-30 21:16:09.884683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed70b125a093'
down_revision: Union[str, Sequence[str], None] = '234839046d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the WalletRole enum type in PostgreSQL
    walletrole_enum = sa.Enum('USER', 'CORE', name='walletrole')
    walletrole_enum.create(op.get_bind(), checkfirst=True)

    # Create wallet_sessions table
    op.create_table('wallet_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('token_jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_sessions_is_revoked'), 'wallet_sessions', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_wallet_sessions_token_jti'), 'wallet_sessions', ['token_jti'], unique=True)
    op.create_index(op.f('ix_wallet_sessions_wallet_id'), 'wallet_sessions', ['wallet_id'], unique=False)

    # Add new columns to wallets table as nullable first (for existing rows)
    op.add_column('wallets', sa.Column('encryption_salt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('wallets', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('wallets', sa.Column('wallet_role', sa.Enum('USER', 'CORE', name='walletrole'), nullable=True))
    op.add_column('wallets', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('wallets', sa.Column('last_unlocked_at', sa.DateTime(), nullable=True))

    # Set default values for existing rows (if any)
    # This handles migration for existing env-based wallets
    op.execute("""
        UPDATE wallets
        SET
            encryption_salt = '__MIGRATION_PLACEHOLDER__',
            password_hash = '__MIGRATION_PLACEHOLDER__',
            wallet_role = 'USER',
            is_locked = TRUE
        WHERE encryption_salt IS NULL
    """)

    # Now alter columns to NOT NULL (safe after setting defaults)
    op.alter_column('wallets', 'encryption_salt', nullable=False)
    op.alter_column('wallets', 'password_hash', nullable=False)
    op.alter_column('wallets', 'wallet_role', nullable=False)
    op.alter_column('wallets', 'is_locked', nullable=False)

    # Create indexes
    op.create_index(op.f('ix_wallets_is_locked'), 'wallets', ['is_locked'], unique=False)
    op.create_index(op.f('ix_wallets_wallet_role'), 'wallets', ['wallet_role'], unique=False)
    # ### end Alembic commands ###

    # Note: Wallets with __MIGRATION_PLACEHOLDER__ values need manual migration
    # They should be recreated with proper passwords and encryption


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_wallet_role'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_is_locked'), table_name='wallets')
    op.drop_column('wallets', 'last_unlocked_at')
    op.drop_column('wallets', 'is_locked')
    op.drop_column('wallets', 'wallet_role')
    op.drop_column('wallets', 'password_hash')
    op.drop_column('wallets', 'encryption_salt')
    op.drop_index(op.f('ix_wallet_sessions_wallet_id'), table_name='wallet_sessions')
    op.drop_index(op.f('ix_wallet_sessions_token_jti'), table_name='wallet_sessions')
    op.drop_index(op.f('ix_wallet_sessions_is_revoked'), table_name='wallet_sessions')
    op.drop_table('wallet_sessions')

    # Drop the WalletRole enum type
    sa.Enum(name='walletrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
